$(document).ready(function(){
	$("#hide").click(function(){
		$("p").hide(1000);
	});
	$("#show").click(function(){
		$("p").show("fast");
	});
	$("#change").click(function(){
		$("p").toggle();
	})
});